name: tdd_structure
description: command line-tool to create TDD project structure.

publish_to: "none"

executables:
  tdd_structure: bin/tdd_structure.dart

version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  args: ^2.3.0
  path: ^1.8.0


dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
